node {
    def hydra

    stage('Clone repository') {
      

        checkout scm
    }

    stage('Build image') {
  
       hydra = docker.build("keyur003/hydra-app")
    }

    stage('Test image') {
  

        hydra-project.inside {
            sh 'echo "Successfully Image created !!"'
        }
    }

    stage('Push image') {
        
        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
            hydra.push("${env.BUILD_NUMBER}")
        }
    }
    
    
}
